Repository ThatConference/thatconference.com, pull requests merged in 2023-12, with the labels that each got.

#146 Feature -> Production
  package.json
  src/_dataSources/api.that.tech/partner/queries.js
  src/routes/(root)/sponsors/+page.svelte
  src/routes/(root)/sponsors/job-board/+page.svelte
  src/routes/(that conferences)/tx/[year]/sponsors/+page.svelte
  src/routes/(that conferences)/wi/[year]/sponsors/+page.svelte
  tsconfig.json
Labels: Feature Release

#148 fix: index correct level
  src/routes/(root)/sponsors/+page.svelte
  src/routes/(that conferences)/tx/[year]/sponsors/+page.svelte
  src/routes/(that conferences)/wi/[year]/sponsors/+page.svelte
Labels: bug

#149 feat: adding page polling and cleanup
  package.json
  src/_components/activityCenter/ActivitySlideOver.svelte
  src/_components/footer/Footer.svelte
  src/lib/stores/notificationCenter.js
  src/routes/+layout.svelte
  svelte.config.js
Labels: enhancement

#150 Feature -> Production
  package.json
  src/_components/activityCenter/ActivitySlideOver.svelte
  src/_components/footer/Footer.svelte
  src/lib/stores/notificationCenter.js
  src/routes/+layout.svelte
  svelte.config.js
Labels: Feature Release

#151 chore: updating chat, fixing type check
  jsconfig.json
  package.json
  src/app.html
  src/routes/+layout.svelte
  tsconfig.json
Labels: bug, chore

#153 refactor: signup page
  .vscode/settings.json
  src/routes/(root)/signup/+page.svelte
  static/images/discord-logo-blue.svg
Labels: enhancement

#154 feature -> production
  .vscode/settings.json
  src/routes/(root)/signup/+page.svelte
  static/images/discord-logo-blue.svg
Labels: Feature Release

#155 feat: adding posthog
  package-lock.json
  package.json
  src/routes/+layout.server.js
  src/routes/+layout.svelte
  vercel.json
Labels: enhancement

#156 feature -> production
  package-lock.json
  package.json
  src/routes/+layout.server.js
  src/routes/+layout.svelte
  vercel.json
Labels: Feature Release

#157 Feat/member sharing on members page
  package.json
  src/_components/members/MemberConnectModal.svelte
  src/_components/members/MemberConnecting.svelte
  src/_dataSources/api.that.tech/memberShareWith/queries.js
  src/_dataSources/api.that.tech/members/mutations.js
  src/_dataSources/api.that.tech/partner/queries.js
  src/_elements/modals/Action.svelte
  src/lib/stores/meFollowing.js
  src/lib/stores/memberSharing.js
  src/routes/(admin my)/my/network/members/+page.server.js
  src/routes/(root)/members/_components/hero.svelte
  src/routes/(root)/sponsors/[partner]/+page.svelte
  src/routes/(root)/sponsors/_components/ShareWithSponsor.svelte
  src/routes/(root)/sponsors/_components/_CTA.svelte
  src/routes/(root)/sponsors/_components/_Hero.svelte
  src/routes/(that conferences)/_components/sponsors/Level.svelte
  src/routes/(that conferences)/tx/[year]/sponsors/+page.svelte
  src/routes/+layout.server.js
  src/routes/+layout.svelte
Labels: enhancement

#158 Feature -> Production
  package.json
  src/_components/members/MemberConnectModal.svelte
  src/_components/members/MemberConnecting.svelte
  src/_dataSources/api.that.tech/memberShareWith/queries.js
  src/_dataSources/api.that.tech/members/mutations.js
  src/_dataSources/api.that.tech/partner/queries.js
  src/_elements/modals/Action.svelte
  src/lib/stores/meFollowing.js
  src/lib/stores/memberSharing.js
  src/routes/(admin my)/my/network/members/+page.server.js
  src/routes/(root)/members/_components/hero.svelte
  src/routes/(root)/sponsors/[partner]/+page.svelte
  src/routes/(root)/sponsors/_components/ShareWithSponsor.svelte
  src/routes/(root)/sponsors/_components/_CTA.svelte
  src/routes/(root)/sponsors/_components/_Hero.svelte
  src/routes/(that conferences)/_components/sponsors/Level.svelte
  src/routes/(that conferences)/tx/[year]/sponsors/+page.svelte
  src/routes/+layout.server.js
  src/routes/+layout.svelte
Labels: Feature Release
