Repository ThatConference/thatconference.com, pull requests merged in 2023-09, with the labels that each got.

#20 fix: profileSlug validation
  src/_components/notifications/CreateProfile.svelte
  src/lib/formSchemas/emergencyContact.js
  src/lib/formSchemas/primaryProfile.js
  src/routes/(admin my)/my/profiles/primary/+page.server.js
  src/routes/(admin my)/my/profiles/primary/+page.svelte
  src/routes/(admin my)/my/profiles/primary/profileForm.svelte
  src/routes/(root)/verify-account/+page.svelte
Labels: bug

#21 fix: clear error message on input
  src/routes/(admin my)/my/profiles/emergency-contact/emergencyContactForm.svelte
Labels: bug

#31 fix: markdown rendering and sentry packages
  mdsvex.config.js
  package-lock.json
  package.json
  svelte.config.js
  vite.config.js
Labels: bug

#35 fix: passkey properties were wrong for current event
  src/lib/config.public.js
Labels: bug

#44 fix: typo in favorites download
  src/routes/(admin my)/my/favorites/+page.svelte
Labels: bug

#48 fix: closes #46
  src/routes/+layout.svelte
Labels: bug

#49 Fixes Isses #41
  src/routes/(admin my)/my/profiles/+layout.svelte
Labels: bug

#50 Refactors and Fixes Event Navigation Issues
  src/_components/navigation/thatConference/EventNav.svelte
  src/_components/navigation/thatConference/MobileEventNav.svelte
  src/_components/navigation/thatConference/MobileNavHat.svelte
  src/_components/navigation/thatConference/Nav.svelte
  src/_components/navigation/thatConference/NavHat.svelte
  src/_components/navigation/thatConference/components/navLink.svelte
  src/routes/(that conferences)/+layout.svelte
  src/routes/(that conferences)/_components/nav/EventNav.svelte
  src/routes/(that conferences)/_components/nav/MobileEventNav.svelte
  src/routes/(that conferences)/_components/nav/MobileNavHat.svelte
  src/routes/(that conferences)/_components/nav/Nav.svelte
  src/routes/(that conferences)/_components/nav/NavHat.svelte
  src/routes/(that conferences)/_components/nav/components/navLink.svelte
Labels: bug, chore

#51 fix: redirects and adds partner redirect
  src/routes/(redirects)/camp/+page.svelte
  src/routes/(redirects)/family/+page.svelte
  src/routes/(redirects)/m/[member]/+page.svelte
  src/routes/(redirects)/partners/[partner]/+page.js
Labels: bug

#52 fix: upnext event card links
  src/_components/events/thatconference/_components/EventCard.svelte
Labels: bug

#53 refactor: partner to sponsor links
  __MIGRATION_TBD__/__events copy__/_components/sponsors/Level.svelte
  src/_components/SponsorSimple.svelte
  src/_components/navigation/default/links.js
  src/routes/(admin sponsor)/sponsor-admin/leads/+page.js
  src/routes/(admin sponsor)/sponsor-admin/leads/[eventId]/+page.svelte
  src/routes/(admin sponsor)/sponsor-admin/my-network/+page.svelte
  src/routes/(root)/sponsors/+page.svelte
  src/routes/(root)/sponsors/[partner]/+page.svelte
  src/routes/(root)/sponsors/[partner]/jobs/[job]/+page.svelte
  src/routes/(root)/sponsors/_components/_EventPartnerLevel.svelte
  src/routes/(root)/sponsors/_components/_JobListings.svelte
  src/routes/(root)/sponsors/_components/_Level.svelte
  src/routes/(root)/sponsors/job-board/+page.svelte
  src/routes/(root)/sponsors/job-board/_components/_JobListCard.svelte
  src/routes/(root)/sponsors/past/+page.svelte
  src/routes/(root)/support/sponsors/forms/+page.svelte
  src/routes/(that conferences)/_components/sponsors/Level.svelte
Labels: bug, chore

#54 fix: enables error page
  src/routes/+error.svelte
Labels: bug

#56 fix: reran sitemap
  static/sitemap.xml
Labels: chore

#57 refactor: removes old layout files
  src/_elements/layouts/ContentLayout.svelte
  src/_elements/layouts/LandingLayout.svelte
  src/_elements/layouts/Simple.svelte
  src/_elements/layouts/StackedLayout.svelte
  src/_elements/layouts/_BaseContent.svelte
Labels: chore

#58 feat: adds event speakers page
  src/_dataSources/api.that.tech/events/queries.js
  src/_elements/layouts/Hero.svelte
  src/routes/(that conferences)/_components/schedule/Hero.svelte
  src/routes/(that conferences)/_components/speakers/Hero.svelte
  src/routes/(that conferences)/tx/[year]/speakers/+page.js
  src/routes/(that conferences)/tx/[year]/speakers/+page.svelte
  src/routes/(that conferences)/tx/[year]/tickets/_components/Hero.svelte
  src/routes/(that conferences)/wi/[year]/speakers/+page.js
  src/routes/(that conferences)/wi/[year]/speakers/+page.svelte
  src/routes/(that conferences)/wi/[year]/tickets/_components/Hero.svelte
  static/images/heros/keynote.jpeg
Labels: enhancement

#63 fix: #37
  src/_components/navigation/default/links.js
Labels: bug

#60 last minute changes
  src/_components/navigation/default/links.js
  src/routes/(root)/_root/components/event.svelte
  src/routes/(root)/_root/components/events.svelte
  src/routes/(root)/_root/components/hero.svelte
  src/routes/(root)/call-for-speakers/_components/eventMeta.svelte
  src/routes/(root)/call-for-speakers/_components/perks.svelte
  src/routes/(root)/orders/_components/_Cart.svelte
  src/routes/(root)/orders/_components/_ClaimCart.svelte
  src/routes/(root)/orders/success/+page.svelte
  src/routes/(root)/support/staying-up-to-date/+page.svelte
  src/routes/(that conferences)/tx/[year]/_components/WhatIs.svelte
  src/routes/(that conferences)/tx/[year]/tickets/_components/Hero.svelte
  src/routes/(that conferences)/tx/[year]/travel/+page.svelte
  src/routes/(that conferences)/wi/[year]/_components/WhatIs.svelte
Labels: Feature Release

#67 adds some usage analytics
  src/_components/newsletter/HubspotForm.svelte
  src/lib/cart/cartMachine.js
  src/routes/(admin my)/my/profiles/emergency-contact/emergencyContactForm.svelte
  src/routes/(admin my)/my/profiles/primary/profileForm.svelte
  src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
  src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte
  src/routes/(root)/orders/_components/_Cart.svelte
Labels: enhancement

#70 fix: event link on mobile drop down menu
  src/_components/navigation/thatConference/MobileEventNav.svelte
Labels: bug

#72 chore - all-contributors
  .all-contributorsrc
  README.md
Labels: chore

#73 fix: action to purge cloudflare on deploy
  .github/workflows/release-success.yml
  package.json
Labels: bug

#74 chore: update sponsor meeting time on order success
  package.json
  src/routes/(root)/orders/success/claim-ticket/+page.svelte
Labels: chore

#76 fix: #75
  src/_elements/links/Action.svelte
  src/routes/(root)/_root/components/hero.svelte
  svelte.config.js
Labels: bug

#77 fix: fixes newsletter modal sizing
  src/_components/newsletter/Modal.svelte
Labels: bug

#82 fix: schedule headers
  src/_components/activities/List.svelte
  src/app.html
  src/routes/+layout.svelte
Labels: bug

#84 Refactor/sourcemaps and env
  package.json
  src/hooks.client.js
  src/hooks.server.js
  src/lib/config.public.js
  vite.config.js
Labels: chore

#85 promote Next/feature to production
  package.json
  src/hooks.client.js
  src/hooks.server.js
  src/lib/config.public.js
  vite.config.js
Labels: chore
