Repository ThatConference/thatconference.com, pull requests merged in 2023-11, with the labels that each got.

#128 Add basic security headers
  package.json
  vercel.json
Labels: chore

#129 promote Next/feature to production
  package.json
  vercel.json
Labels: chore

#130 Chore/sentry deny urls
  package.json
  src/hooks.client.js
  src/hooks.server.js
  src/lib/config.public.js
Labels: chore, add-to-that.us

#131 promote Next/feature to production
  package.json
  src/hooks.client.js
  src/hooks.server.js
  src/lib/config.public.js
Labels: chore

#134 fix: sponsor links on sponsor resource form
  package.json
  src/routes/(root)/support/sponsors/forms/+page.svelte
Labels: bug

#81 feat: add draft convince your boss page
  src/_dataSources/api.that.tech/events/queries.js
  src/routes/(admin my)/my/profiles/primary/profileForm.svelte
  src/routes/(root)/support/convince-your-boss/+page.js
  src/routes/(root)/support/convince-your-boss/+page.svelte
  src/routes/(root)/support/convince-your-boss/_components/EventLink.svelte
Labels: Feature Release

#135 Chore: updating sitemap and analytics
  src/app.html
  src/lib/tagEvent.js
  static/sitemap.xml
Labels: chore

#137 feat: adds blog
  package-lock.json
  package.json
  src/_components/navigation/default/Base.svelte
  src/_elements/links/Standard.svelte
  src/lib/config.public.js
  src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
  src/routes/(root)/blog/+layout.js
  src/routes/(root)/blog/+page.js
  src/routes/(root)/blog/+page.svelte
  src/routes/(root)/blog/[article]/+page.js
  src/routes/(root)/blog/[article]/+page.svelte
  src/routes/(root)/blog/components/ArticleCard.svelte
Labels: enhancement

#138 Feature -> Production
  package-lock.json
  package.json
  src/_components/navigation/default/Base.svelte
  src/_elements/links/Standard.svelte
  src/lib/config.public.js
  src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
  src/routes/(root)/blog/+layout.js
  src/routes/(root)/blog/+page.js
  src/routes/(root)/blog/+page.svelte
  src/routes/(root)/blog/[article]/+page.js
  src/routes/(root)/blog/[article]/+page.svelte
  src/routes/(root)/blog/components/ArticleCard.svelte
Labels: Feature Release

#139 fix: viewport
  src/app.html
Labels: bug

#140 fix: links
  package.json
  src/_components/footer/links.js
  src/_components/navigation/default/Base.svelte
  src/_components/navigation/default/links.js
Labels: bug

#141 fix: issue where partner contact is null
  package.json
  src/routes/(admin my)/my/network/sponsors/+page.svelte
Labels: bug, add-to-that.us

#142 feat: member–member sharing of shared profile data
  package.json
  src/_dataSources/api.that.tech/memberShareWith/mutations.js
  src/_dataSources/api.that.tech/memberShareWith/queries.js
  src/_elements/buttons/ActionShell.svelte
  src/_elements/buttons/DisabledShell.svelte
  src/_elements/buttons/Standard.svelte
  src/_elements/buttons/index.js
  src/lib/formSchemas/sharingForm.js
  src/routes/(admin my)/my/_components/PageLayout.svelte
  src/routes/(admin my)/my/_components/ShareDetailsModal.svelte
  src/routes/(admin my)/my/_components/SharingRow.svelte
  src/routes/(admin my)/my/member-sharing/+page.svelte
  src/routes/(admin my)/my/member-sharing/[eventId]/+layout@.svelte
  src/routes/(admin my)/my/member-sharing/[eventId]/+page.server.js
  src/routes/(admin my)/my/member-sharing/[eventId]/+page.svelte
  src/routes/(admin my)/my/network/+layout.svelte
  src/routes/(admin my)/my/network/members/+page.server.js
  src/routes/(admin my)/my/network/members/+page.svelte
Labels: enhancement

#143 Promote Next/feature to production
  package.json
  src/_dataSources/api.that.tech/memberShareWith/mutations.js
  src/_dataSources/api.that.tech/memberShareWith/queries.js
  src/_elements/buttons/ActionShell.svelte
  src/_elements/buttons/DisabledShell.svelte
  src/_elements/buttons/Standard.svelte
  src/_elements/buttons/index.js
  src/lib/formSchemas/sharingForm.js
  src/routes/(admin my)/my/_components/PageLayout.svelte
  src/routes/(admin my)/my/_components/ShareDetailsModal.svelte
  src/routes/(admin my)/my/_components/SharingRow.svelte
  src/routes/(admin my)/my/member-sharing/+page.svelte
  src/routes/(admin my)/my/member-sharing/[eventId]/+layout@.svelte
  src/routes/(admin my)/my/member-sharing/[eventId]/+page.server.js
  src/routes/(admin my)/my/member-sharing/[eventId]/+page.svelte
  src/routes/(admin my)/my/network/+layout.svelte
  src/routes/(admin my)/my/network/members/+page.server.js
  src/routes/(admin my)/my/network/members/+page.svelte
Labels: enhancement
