Repository ThatConference/thatconference.com, pull requests merged in 2023-10, with the labels that each got.

#87 Promote Next/feature to production
  src/_components/navigation/thatConference/EventNav.svelte
Labels: Feature Release

#89 Refactor order success page
  .github/workflows/release-success.yml
  package.json
  src/_elements/links/Standard.svelte
  src/lib/formSchemas/sharedProfile.js
  src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte
  src/routes/(root)/orders/_components/_Cart.svelte
  src/routes/(root)/orders/canceled/+page.svelte
  src/routes/(root)/orders/success/+page.svelte
  src/routes/(root)/orders/success/claim-ticket/+page.svelte
  src/routes/(root)/support/staying-up-to-date/+page.svelte
  src/routes/(root)/support/transfer-a-ticket/+page.svelte
Labels: bug, chore, enhancement

#91 Promote Next/feature to production
  .github/workflows/release-success.yml
  package.json
  src/_elements/links/Standard.svelte
  src/lib/formSchemas/sharedProfile.js
  src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte
  src/routes/(root)/orders/_components/_Cart.svelte
  src/routes/(root)/orders/canceled/+page.svelte
  src/routes/(root)/orders/success/+page.svelte
  src/routes/(root)/orders/success/claim-ticket/+page.svelte
  src/routes/(root)/support/staying-up-to-date/+page.svelte
  src/routes/(root)/support/transfer-a-ticket/+page.svelte
Labels: bug, chore, enhancement

#92 fix session list filter
  package.json
  src/_components/activities/List.svelte
Labels: bug

#94 promote Next/feature to production
  package.json
  src/_components/activities/List.svelte
Labels: bug, add-to-that.us

#95 get leads working on thatconference.com
  package.json
  src/lib/config.public.js
  src/routes/(admin sponsor)/sponsor-admin/leads/+page.js
  src/routes/(admin sponsor)/sponsor-admin/leads/+page.svelte
  src/routes/(admin sponsor)/sponsor-admin/leads/[eventId]/+page.svelte
  src/routes/(root)/support/sponsors/forms/+page.svelte
Labels: chore, enhancement

#96 Promote Next/feature to production
  package.json
  src/lib/config.public.js
  src/routes/(admin sponsor)/sponsor-admin/leads/+page.js
  src/routes/(admin sponsor)/sponsor-admin/leads/+page.svelte
  src/routes/(admin sponsor)/sponsor-admin/leads/[eventId]/+page.svelte
  src/routes/(root)/support/sponsors/forms/+page.svelte
Labels: chore, enhancement

#97 THAT Check-in
  package-lock.json
  package.json
  src/routes/(admin)/admin/check-in/_components/_CheckinModal.svelte
  src/routes/(admin)/admin/check-in/_components/_EditCheckInModal.svelte
  src/routes/(admin)/admin/check-in/_components/_Ticket.svelte
  src/routes/(admin)/admin/check-in/_components/_TicketView.svelte
Labels: chore

#99 fix: routes to non-existend events
  package.json
  src/routes/(that conference online)/[event]/[date]/+layout.js
  src/routes/(that conference online)/_components/EventTicket.svelte
  src/routes/(that conference online)/_components/OnlineHero.svelte
  src/routes/(that conferences)/+layout.js
Labels: bug

#100 Promote Next/feature to production
  package-lock.json
  package.json
  src/routes/(admin)/admin/check-in/_components/_CheckinModal.svelte
  src/routes/(admin)/admin/check-in/_components/_EditCheckInModal.svelte
  src/routes/(admin)/admin/check-in/_components/_Ticket.svelte
  src/routes/(admin)/admin/check-in/_components/_TicketView.svelte
  src/routes/(that conference online)/[event]/[date]/+layout.js
  src/routes/(that conference online)/_components/EventTicket.svelte
  src/routes/(that conference online)/_components/OnlineHero.svelte
  src/routes/(that conferences)/+layout.js
Labels: bug, chore

#101 fix: fetch r.ok
  package.json
  src/lib/gfetch.js
Labels: bug

#104 Feature -> production
  src/routes/+layout.svelte
Labels: Feature Release

#106 Feat/add svelte auth
  package-lock.json
  package.json
  src/_components/footer/links.js
  src/_components/navigation/_components/MobileUsersProfile.svelte
  src/_components/navigation/_components/UserProfile.svelte
  src/_dataSources/api.that.tech/partner/leads/mutations.js
  src/hooks.client.js
  src/hooks.server.js
  src/lib/config.public.js
  src/lib/security/auth.js
  src/lib/security/client.js
  src/lib/security/server.js
  src/lib/security/wrappers.js
  src/lib/svelteAuth/parseJwt.js
  src/routes/(admin my)/my/+layout.js
  src/routes/(admin my)/my/+layout.server.js
  src/routes/(admin sponsor)/sponsor-admin/leads/+layout.js
  src/routes/(admin sponsor)/sponsor-admin/leads/[eventId]/+page.server.js
  src/routes/(admin sponsor)/sponsor-admin/my-network/+layout.js
  src/routes/(admin sponsor)/sponsor-admin/my-network/+page.server.js
  src/routes/(admin)/admin/+layout.js
  src/routes/(admin)/admin/check-in/[eventName]/[year]/+page.server.js
  src/routes/(root)/login-redirect/+page.svelte
  src/routes/(root)/login/+server.js
  src/routes/(root)/logout/+server.js
  src/routes/(root)/signup/+page.server.js
  src/routes/(root)/signup/+page.svelte
  src/routes/(root)/speakers/+layout.js
  src/routes/(root)/speakers/+layout.server.js
  src/routes/+layout.server.js
  src/routes/api/auth/callback/+server.js
  src/routes/api/auth/me/+server.js
  src/routes/api/auth/proxy/+server.js
  src/routes/api/auth/signup/+server.js
Labels: enhancement

#112 refactor: scrollto on save
  package.json
  src/routes/(admin my)/my/profiles/emergency-contact/emergencyContactForm.svelte
  src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
  src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte
Labels: enhancement

#114 refactor: adding snapshots to forms
  package.json
  src/_components/newsletter/HubspotForm.svelte
  src/routes/(admin my)/my/profiles/emergency-contact/emergencyContactForm.svelte
  src/routes/(admin my)/my/profiles/primary/profileForm.svelte
  src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
  src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte
Labels: enhancement

#115 feature -> production
  package.json
  src/_components/newsletter/HubspotForm.svelte
  src/routes/(admin my)/my/profiles/emergency-contact/emergencyContactForm.svelte
  src/routes/(admin my)/my/profiles/primary/profileForm.svelte
  src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
  src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte
Labels: enhancement

#116 fix: check for verified emails on auth'd paths
  package.json
  src/hooks.server.js
Labels: bug, regression

#117 Promote Next/feature to Production
  package.json
  src/hooks.server.js
Labels: bug, regression

#119 fix: http 401 on favorites
  __MIGRATION_TBD__/__events copy__/(thatConferences)/_components/nav/NavHat.svelte
  package.json
  src/_components/navigation/thatConference/NavHat.svelte
  src/lib/stores/favorites.js
Labels: bug

#121 fix: references of /events/{slug} to /{slug}
  package.json
  src/_components/activities/ActivityDetails.svelte
  src/_components/cta/_HomePageCFP.svelte
  src/_components/cta/_TicketsOnSale.svelte
  src/_components/navigation/thatConference/NavHat.svelte
  src/routes/(redirects)/family/+page.js
  src/routes/(that conference online)/[event]/[date]/+page.svelte
  src/routes/(that conferences)/tx/[year]/+page.svelte
  src/routes/(that conferences)/tx/[year]/_components/CamperTickets.svelte
  src/routes/(that conferences)/tx/[year]/schedule/+page.svelte
  src/routes/(that conferences)/tx/[year]/sponsors/+page.svelte
  src/routes/(that conferences)/tx/[year]/tickets/+page.svelte
  src/routes/(that conferences)/wi/[year]/_components/CamperTickets.svelte
Labels: bug

#122 refactor: /membership route to that.us in the short term
  package.json
  src/routes/(redirects)/membership/+page.js
  src/routes/(root)/_root/components/ctaMembership.svelte
Labels: bug, chore

#124 chore: adding new images for texas
  package.json
  src/routes/(that conferences)/tx/[year]/_components/Gallery.svelte
  static/images/gallery/tx/52682413507.jpeg
  static/images/gallery/tx/52682420922.jpeg
  static/images/gallery/tx/52682422662.jpeg
  static/images/gallery/tx/52682425742.jpeg
  static/images/gallery/tx/52682924066.jpeg
  static/images/gallery/tx/52682929266.jpeg
  static/images/gallery/tx/52682929506.jpeg
  static/images/gallery/tx/52682944046.jpeg
  static/images/gallery/tx/52683217939.jpeg
  static/images/gallery/tx/52683232524.jpeg
  static/images/gallery/tx/52683359850.jpeg
  static/images/gallery/tx/52683376215.jpeg
  static/images/gallery/tx/52683376855.jpeg
  static/images/gallery/tx/52683380625.jpeg
  static/images/gallery/tx/52683441438.jpeg
  static/images/gallery/tx/52683450183.jpeg
Labels: chore

#125 feature -> prod
  package.json
  src/routes/(that conferences)/tx/[year]/_components/Gallery.svelte
  static/images/gallery/tx/52682413507.jpeg
  static/images/gallery/tx/52682420922.jpeg
  static/images/gallery/tx/52682422662.jpeg
  static/images/gallery/tx/52682425742.jpeg
  static/images/gallery/tx/52682924066.jpeg
  static/images/gallery/tx/52682929266.jpeg
  static/images/gallery/tx/52682929506.jpeg
  static/images/gallery/tx/52682944046.jpeg
  static/images/gallery/tx/52683217939.jpeg
  static/images/gallery/tx/52683232524.jpeg
  static/images/gallery/tx/52683359850.jpeg
  static/images/gallery/tx/52683376215.jpeg
  static/images/gallery/tx/52683376855.jpeg
  static/images/gallery/tx/52683380625.jpeg
  static/images/gallery/tx/52683441438.jpeg
  static/images/gallery/tx/52683450183.jpeg
Labels: Feature Release
